In [1]:
from keras.models import Model
from keras.layers import Dense, Input
from keras.utils import to_categorical

import numpy as np

Using TensorFlow backend.


In [2]:
# Generate dummy data

x_train = np.random.random((1000, 20))
y_train = np.random.randint(10, size=(1000, 1))
x_test = np.random.random((200, 20))
y_test = np.random.randint(10, size=(200, 1))

print(y_train[0:5, :])
print(x_train[0:2, :])

# Convert labels to categorical one-hot encoding
y_train_ohe = to_categorical(y_train, num_classes=10)
y_test_ohe = to_categorical(y_test, num_classes=10)

[[9]
 [4]
 [1]
 [6]
 [4]]
[[0.4260757  0.97016817 0.56700548 0.77483474 0.80175619 0.18662985
  0.98738945 0.40649317 0.63022438 0.07019245 0.35246198 0.11609084
  0.43244173 0.0993395  0.08367933 0.96891536 0.11963106 0.31862076
  0.96993631 0.03067292]
 [0.64142643 0.27605086 0.32574678 0.68082781 0.03436235 0.00223927
  0.17994769 0.76094061 0.7402233  0.17702353 0.39211967 0.47902175
  0.21448099 0.37657446 0.23741831 0.3287149  0.92933867 0.4489591
  0.13131606 0.11096802]]


In [3]:
# For a single-input model with 10 classes (categorical classification):

input_1 = Input(shape=(20,))

# a layer instance is callable on a tensor, and returns a tensor
output_1 = Dense(32, activation='relu')(input_1)
output_2 = Dense(32, activation='relu')(output_1)
predictions = Dense(10, activation='softmax')(output_2)

# model includes the Input layer and three Dense layers
model = Model(inputs=input_1, outputs=predictions)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [4]:
model.fit(x_train, y_train_ohe, batch_size=32, epochs=10)

score = model.evaluate(x_test, y_test_ohe, batch_size=32)
print(score)

Epoch 1/10
1000/1000 [==============================] - 0s 184us/step - loss: 2.3278 - accuracy: 0.0880
Epoch 2/10
1000/1000 [==============================] - 0s 207us/step - loss: 2.3053 - accuracy: 0.1010
Epoch 3/10
1000/1000 [==============================] - 0s 130us/step - loss: 2.2973 - accuracy: 0.1090

In [5]:
y_pred = model.predict(x_test, batch_size=32)

In [6]:
print(y_pred)
print(y_test_ohe)


[[0.09291678 0.06259153 0.11213051 ... 0.11714195 0.10019346 0.12476508]
 [0.09623317 0.10706423 0.10694236 ... 0.09014204 0.10857182 0.10393586]
 [0.09788359 0.08487371 0.11762002 ... 0.10255612 0.10381296 0.11691079]
 ...
 [0.08475105 0.0770512  0.13857035 ... 0.08799926 0.10113905 0.11311923]
 [0.0931185  0.09704416 0.10001757 ... 0.09729744 0.10518374 0.11479395]
 [0.126557   0.06385301 0.11776559 ... 0.11099712 0.0913347  0.10817408]]
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
