In [11]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from keras.optimizers import SGD

import numpy as np

In [12]:
# Generate dummy data

x_train = np.random.random((1000, 20))
y_train = np.random.randint(10, size=(1000, 1))
x_test = np.random.random((200, 20))
y_test = np.random.randint(10, size=(200, 1))

print(y_train[0:5, :])
print(x_train[0:2, :])

# Convert labels to categorical one-hot encoding
y_train_ohe = to_categorical(y_train, num_classes=10)
y_test_ohe = to_categorical(y_test, num_classes=10)

[[2]
 [7]
 [5]
 [8]
 [3]]
[[0.57861381 0.8317938  0.11401128 0.47274288 0.71622228 0.07421284
  0.64971298 0.78507574 0.65746371 0.33380442 0.57983673 0.81787487
  0.48888273 0.11859549 0.65651989 0.82316983 0.85104156 0.28237781
  0.16616137 0.71141481]
 [0.29797797 0.746447   0.67585911 0.48024854 0.08538422 0.68346823
  0.37786392 0.62903241 0.58314118 0.45397363 0.40896638 0.19535997
  0.45225306 0.57248559 0.04622998 0.28998485 0.7148882  0.858192
  0.46721854 0.36801189]]


In [13]:
# For a single-input model with 10 classes (categorical classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train_ohe, batch_size=32, epochs=10)

score = model.evaluate(x_test, y_test_ohe, batch_size=32)
print(score)

Epoch 1/10
1000/1000 [==============================] - 0s 190us/step - loss: 2.3874 - accuracy: 0.0960
Epoch 2/10
1000/1000 [==============================] - 0s 132us/step - loss: 2.3111 - accuracy: 0.1010
Epoch 3/10
1000/1000 [==============================] - 0s 104us/step - loss: 2.3043 - accuracy: 0.1170
Epoch 4/10
1000/1000 [==============================] - 0s 153us/step - loss: 2.3016 - accuracy: 0.1190

In [15]:
y_pred = model.predict(x_test, batch_size=32)

In [16]:
print(y_pred)
print(y_test_ohe)


[[0.09436669 0.10611275 0.11243737 ... 0.08991478 0.09793793 0.08998977]
 [0.09372142 0.10571487 0.11303346 ... 0.0892712  0.09733778 0.09060805]
 [0.0934437  0.10629782 0.11281627 ... 0.09028134 0.09856725 0.09262258]
 ...
 [0.09591044 0.10180692 0.1207167  ... 0.08683373 0.09390771 0.09112604]
 [0.09178582 0.10290925 0.11517166 ... 0.09018073 0.09769564 0.0888156 ]
 [0.09284444 0.10646971 0.11253582 ... 0.08933692 0.09577393 0.09174536]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
